### ISSUE TITLE
Resolve Rails 7.1 Test Compatibility Issue

### ISSUE THREAD

**Issue by TheMetalCode** [doximity/super_spreader#60]
[Example failing specs when using Rails 7.1](https://app.circleci.com/pipelines/github/doximity/super_spreader/135/workflows/b174a131-470a-4c2c-bc07-b8af61ba9f26/jobs/603/tests#failed-test-0)

```bash
Failure/Error:
  perform_enqueued_jobs do
    SuperSpreader::SchedulerJob.perform_now
  end

NameError:
  uninitialized constant ActiveSupport::Testing::Assertions::Minitest
./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3/lib/active_support/testing/assertions.rb:267:in `rescue in _assert_nothing_raised_or_warn'
./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3/lib/active_support/testing/assertions.rb:265:in `_assert_nothing_raised_or_warn'
./vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3/lib/active_job/test_helper.rb:628:in `perform_enqueued_jobs'
./spec/integration/backfill_spec.rb:50:in `block (3 levels) in <top (required)>'
./spec/support/log_spec_helper.rb:11:in `capture_log'
./spec/integration/backfill_spec.rb:49:in `block (2 levels) in <top (required)>'
./spec/spec_helper.rb:62:in `block (2 levels) in <top (required)>'
------------------
--- Caused by: ---
NoMethodError:
  undefined method `assert' for #<RSpec::ExampleGroups::Integration:0x00007f519e71c450>
  ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3/lib/active_support/testing/assertions.rb:49:in `block in assert_nothing_raised'
```

**Comment by benjaminoakes** [comment]
My apologies.  I didn't realize we already have an issue for this: https://github.com/doximity/super_spreader/issues/55
